const  data = [
    {
    "id": "1",
    "name": "Pradhan Mantri Awas Yojana",
    "category" :["Housing"],
    "gender":["All"], 
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Pradhan Mantri Awas Yojana – Urban (PMAY-U), a flagship Mission of Government of India being implemented by Ministry of Housing and Urban Affairs.", 
    "longDescription" : "The Mission addresses urban housing shortage among the EWS/LIG and MIG categories including the slum dwellers by ensuring a pucca house to all eligible urban households by the year 2022, when Nation completes 75 years of its Independence", 
    "eligibility" : ["The Applicant’s Family must not own a house in any part of the country.", "In the case of a Married couple, either a Single or a Joint ownership deal is allowed, and both options will receive just one subsidy.", "The Applicant’s Family must not have availed the benefit of any housing-related schemes set up by the Government of India."], 
    "implementedBy" : "Ministry of Housing and Urban Affairs", 
    "link" : ""
    },
    {
    "id": "2",
    "name": "Pradhan Mantri Vaya Vandana Yojana",
    "category" :["Pension"],
    "gender":["All"],
    "disability":["No"],
    "age":[60],
    "ageLowerLimit": 60, 
    "ageHigherLimit" : 130,
    "shortDescription" : "Launched by the GOI to protect elderly persons aged 60 years and above against a future fall in their interest income due to uncertain market conditions, as also to provide social security during old age", 
    "longDescription" : "The scheme is implemented through the Life Insurance Corporation of India (LIC) and open for subscription upto 31st March, 2023.", 
    "eligibility" : ["Elderly persons aged 60 years and above"], 
    "implementedBy" : "Life Insurance Corporation of India (LIC)", 
    "link" : "https://licindia.in/Products/Pension-Plans/Pradhan-Mantri-Vaya-Vandana-Yojana1 "
    },
    {
    "id": "3",
    "name": "Rashtriya Vayoshri Yojana (RVY)",
    "category" :["Pension", "Disability", "BPL"],
    "gender":["All"],
    "disability":["Yes"],
    "age":[60],
    "ageLowerLimit": 60, 
    "ageHigherLimit" : 130,
    "shortDescription" : "Launched in 2017 by the Ministry of Social Justice & Empowerment of Government of India .", 
    "longDescription" : "This scheme for providing Physical Aids and Assisted-living Devices for Senior citizens belonging to BPL category. This is a Central Sector Scheme, fully funded by the Central Government. The expenditure for implementation of the scheme will be met from the Senior Citizens Welfare Fund", 
    "eligibility" : ["Senior Citizens, belonging to BPL category and suffering from any of the age related disability/infirmity viz. Low vision, Hearing impairment, Loss of teeth and Locomotor disability will be provided with such assisted-living devices which can restore near normalcy in their bodily functions, overcoming the disability/infirmity manifested.", "The Scheme is expected to benefit all Senior Citizens across the country. "], 
    "implementedBy" : "Ministry of Social Justice & Empowerment", 
    "link" : "https://www.india.gov.in/spotlight/rashtriya-vayoshri-yojana"
    },
    {
    "id": "4",
    "name": "Monthly Pension scheme for older person",
    "category" :["Pension", "BPL"],
    "gender":["All"],
    "disability":["No"],
    "age":[65],
    "ageLowerLimit": 65, 
    "ageHigherLimit" : 130,
    "shortDescription" : "In this Scheme Rs. 400/- is given as monthly pension to needy elderly persons to maintained themselves:", 
    "longDescription" : "", 
    "eligibility" : ["He / She should be 65 years or more in age.", "The combined annual income of the proposed pensioner and his or her spouse shall not exceed Rs.20,000/- as certified by the local revenue authority."], 
    "implementedBy" : "", 
    "link" : "https://sevasindhu.karnataka.gov.in/ "
    },
    {
    "id": "5",
    "name": "Sandhya Suraksha Scheme",
    "category" :["Pension", "BPL"],
    "gender":["All"],
    "disability":["No"],
    "age":[65],
    "ageLowerLimit": 65, 
    "ageHigherLimit" : 130,
    "shortDescription" : "The purpose of the scheme to provide some relief to the age to providing financial assistance in the form of social security pension.  Person will get monthly amount from Govt. of Karnataka ", 
    "longDescription" : "The beneficiaries under this scheme will be chosen from the following categories - a. Small farmers b. Marginal farmers,  Agricultural labourers,  Weavers,   Fishermen ", 
    "eligibility" : [" He / She should be 65 years or more in age.", "he combined annual income of the proposed pensioner and his or her spouse shall not exceed Rs.20,000/- as certified by the local revenue authority.", "he combined annual income of the proposed pensioner and his or her spouse shall not exceed Rs.20,000/- as certified by the local revenue authority.", "The total value of combined deposits held by the pensioner and his spouse shall not exceeding Rs.10,000/-.", "Such of the persons availing of old age pension, Destitute widow pension or physically handicapped pension or any other form of pension from public or private sources are not eligible for this scheme."], 
    "implementedBy" : "", 
    "link" : "www.sevasindhu.karnataka.gov.in"
    },
    {
    "id": "6",
    "name": "Manaswini Yojana",
    "category" :["Women"],
    "gender":["Women", "BPL"],
    "disability":["No"],
    "age":[40],
    "ageLowerLimit": 40, 
    "ageHigherLimit" : 64,
    "shortDescription" : "The objective of Manaswini Scheme is to protect poor unmarried, separated and divorced women in rural areas who suffer from social taboo without any freedom to participate in the socio-economic development of Karnataka.", 
    "longDescription" : "Poor women usually lack economic support from their respective families. Taking this into consideration these aspects and to lend a helping hand for their sustenance, Government of Karnataka launched Manaswini schem", 
    "eligibility" : ["Women from BPL family aged above 40 to 64 years"], 
    "implementedBy" : "", 
    "link" : "https://sevasindhu.karnataka.gov.in/ "
    },
    {
    "id": "7",
    "name": "Physically Handicapped Pension",
    "category" :["Pension", "Disability", "BPL"],
    "gender":["All"],
    "disability":["Yes"],
    "age":[16],
    "ageLowerLimit": 16, 
    "ageHigherLimit" : 130,
    "shortDescription" : "The disability pension is administered by the revenue department of Karnataka and is termed as monthly maintenance allowance.", 
    "longDescription" : "There are two categories of allowance one is given to those who have disability below 75 % and are given INR 400 per month. Those persons with disabilities who have above 75% disability are given INR 1000 per month. This is fusion of Indira Gandhi National Disability Pension Scheme.", 
    "eligibility" : ["Income should be less than INR 11,500/- per anum and INR 24000 per anum in Rural as well  as in urban area respectively,  Resident of  Karnataka at least  since last 10 years,  Above 16 years"], 
    "implementedBy" : "Revenue department of Karnataka", 
    "link" : "https://sevasindhu.karnataka.gov.in/"
    },
    {
    "id": "8",
    "name": "Maitri Scheme",
    "category" :["Transgender", "BPL"],
    "gender":["Transgender"],
    "disability":["No"],
    "age":[25],
    "ageLowerLimit": 25, 
    "ageHigherLimit" : 64,
    "shortDescription" : "To help transgender community and bring them to the mainstream Govt. of Karnataka introduced this scheme.", 
    "longDescription" : "Transgender people with annual income less than Rs. 12,000 per annum in rural areas and Rs. 17,000 per annum in urban areas will be eligible for the scheme. They will be required to submit relevant documents including a certificate from the Department of Health and Family Welfare to prove their gender.", 
    "eligibility" : ["Transgenders below Poverty line aged 25 to 64 years"], 
    "implementedBy" : "", 
    "link" : "https://sevasindhu.karnataka.gov.in/"
    },
    {
    "id": "9",
    "name": "PM Matru vandana",
    "category" :["Women", "Health"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Pradhan Mantri Matru Vandana Yojana is a Centrally Sponsored DBT scheme with the cash incentive of ₹ 5000/- (in three instalments) being provided directly in the bank/post office account of Pregnant Women and Lactating Mothers.", 
    "longDescription" : "", 
    "eligibility" : ["Lactating mothers and pregnant women in case of the birth of the first child in the family."], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "10",
    "name": "POSHAN Abhiyan",
    "category" :["Women", "Health"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "POSHAN Abhiyaan or National Nutrition Mission, is Government of India’s flagship programme to improve nutritional outcomes for children, pregnant women and lactating mothers.", 
    "longDescription" : "The POSHAN  Abhiyaan directs the attention of the country towards the problem of malnutrition and address it in a mission-mode.", 
    "eligibility" : "", 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "11",
    "name": "Ayushman Bharat",
    "category" :["Health", "BPL"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (PM-JAY), is a flagship scheme of Government of India to provide cashless secondary and tertiary care treatment from the empanelled public and private hospitals providing coverage to more than 10 crore poor and vulnerable beneficiary families.", 
    "longDescription" : "", 
    "eligibility" : ["All BPL card holders"], 
    "implementedBy" : "", 
    "link" : "https://pmjay.gov.in/ "
    },
    {
    "id": "12",
    "name": "Arogya Karnataka",
    "category" :["Health"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "The objective of Arogya Karnataka scheme is to expand ‘Universal Health Coverage’ to all residents in the Karnataka State.", 
    "longDescription" : "Under this scheme, specified secondary and tertiary health care, primary health care benefits will be provided by the government", 
    "eligibility" : ["All the residents of Karnataka state are eligible for arogya Karnataka scheme. Beneficiaries listed in SECC data are also eligible.", "Those who have already enrolled for Rashtriya Swasthya Bhima Yojana can also apply for this scheme"], 
    "implementedBy" : "", 
    "link" : "https://arogya.karnataka.gov.in/"
    },
    {
    "id": "13",
    "name": "AICTE – Swanth Scholorship Scheme",
    "category" :["Students"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "AICTE has approved 'AICTE – SWANATH SCHOLARSHIP SCHEME' for children", 
    "longDescription" : "from any one of the following categories: 1. Orphan  2. Either or both parents died due to Covid-193. Wards of Armed Forces and Central Paramilitary Forces martyred in action (Shaheed) to provide them financial support of Rs. 50,000/- per annum for every year of study.", 
    "eligibility" : ["1. Orphan 2. Either or both parents died due to Covid-19 3. Wards of Armed Forces and Central Paramilitary Forces martyred in action (Shaheed)"], 
    "implementedBy" : "", 
    "link" : "https://scholarships.gov.in/"
    },
    {
    "id": "14",
    "name": "PG Scholorship",
    "category" :["Students"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Scholarship is awarded to full time GATE/GPAT qualified students admitted to M.E./ M. Tech/ M. Arch and M.Pharma courses in AICTE approved Institutions/Colleges @Rs. 12,400/- PM/ student.", 
    "longDescription" : "", 
    "eligibility" : [""], 
    "implementedBy" : "", 
    "link" : "https://scholarships.gov.in/"
    },
    {
    "id": "15",
    "name": "Pragati Scholorship",
    "category" :["Women", "Students"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Scholarship/Contingency is awarded to meritorious girls taking admission in AICTE approved Technical institution at Degree/ Diploma.", 
    "longDescription" : "Total 10000 scholarship are given @ Rs 50000 as incidentals each year.", 
    "eligibility" : [""], 
    "implementedBy" : "", 
    "link" : "https://scholarships.gov.in/"
    },
    {
    "id": "16",
    "name": "Prime Minister's Special Scholorship Scheme – PMSSS",
    "category" :["Students"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "Objective of the Scheme is to build up capacities in youth of J&K, educate, enable and empowering them to compete in normal course, enhancing and boosting employment potentials in students of J&K", 
    "longDescription" : "Total 5000 scholarship are given @ Rs. 100000/- as Maintenance Charges and academic fee as Rs. 30000/- to General Degree, Rs. 125000/- to Engineering Degree & Rs. 300000/- to Medical Degree each year.", 
    "eligibility" : [""], 
    "implementedBy" : "", 
    "link" : "https://scholarships.gov.in/"
    },
    {
    "id": "17",
    "name": "Chief Minister Raitha Vidyanidhi Scheme",
    "category" :["Women", "Students"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "A prominent decision taken by the Chief Minister in his very first cabinet meeting immediately after assuming office is the ‘CM’s Raitha Vidya Nidhi’ programme to disburse scholarships for students from farmers’ families.", 
    "longDescription" : "Under this scheme scholarships are being disbursed for girl students from farmers’ families studying in class 8, 9 and 10 and also to farmers’ children studying in PUC, Diploma, ITI", 
    "eligibility" : [""], 
    "implementedBy" : "", 
    "link" : "https://raitamitra.karnataka.gov.in/"
    },
    {
    "id": "18",
    "name": "National Apprenticeship Promotion Scheme",
    "category" :["Students", "Skill Development"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "NAPS was launched in August 2016 by Government of India to promote the Apprenticeship in the country by providing financial incentives, technology and advocacy support.", 
    "longDescription" : "1. Sharing of 25% of prescribed stipend subject to a maximum of Rs. 1500/- per month per apprentice with the employers.2. Sharing of basic training cost up to a maximum of Rs. 7,500 per apprentice.", 
    "eligibility" : ["Apprentice must register on the portal.", "Apprentice must have an aadhaar number.", "Maximum age in respect of fresher apprentice shall be 21 years"], 
    "implementedBy" : "", 
    "link" : "https://www.apprenticeshipindia.gov.in/ "
    },
    {
    "id": "19",
    "name": "Working Women Hostel",
    "category" :["Women"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "The Government of India has launched “Working Women Hostel Scheme” to promote the availability of reliable and conveniently located accommodation for the working women who are leaving their homes due to professional commitments.", 
    "longDescription" : "Under this scheme, the Government provides a grant-in-aid for the construction of new or expansion of existing buildings to advance hostel facilities in cities, towns and also in rural areas.", 
    "eligibility" : ["Widowed, Physically Handicapped, Single, Separated Women Are Allowed"], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "20",
    "name": "Ujjwala",
    "category" :["Other", "Housing"],
    "gender":["All"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "t is  a flagship scheme of Govt. of India with an objective to make clean cooking fuel such as LPG available to the rural and deprived households which were otherwise using traditional cooking fuels such as firewood, coal, cow-dung cakes etc.", 
    "longDescription" : "Usage of traditional cooking fuels had detrimental impacts on the health of rural women as well as on the environment.", 
    "eligibility" : ["SC, ST Households, Most Backward Classes, Antyodaya Anna Yojana (AAY)", "Tea and Ex- Tea Garden tribes, Forest Dwellers", "People residing in Islands and River Islands, SECC Households ,Applicant must have attained 18 years of age.", "There should not be any other LPG connections in the same household."], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "21",
    "name": "One Stop One Center",
    "category" :["Women"],
    "gender":["Women"],
    "disability":["No"],
    "age":["All"],
    "ageLowerLimit": "All", 
    "ageHigherLimit" : "All",
    "shortDescription" : "One Stop Centres are intended to support women affected by violence, in private and public spaces, within the family, community and at the workplace.", 
    "longDescription" : "Women facing physical, sexual, emotional, psychological and economic abuse, irrespective of age, class, caste, education status, marital status, race and culture will be facilitated with support and redressal. Aggrieved women facing any kind of violence due to attempted sexual harassment, sexual assault, domestic violence, trafficking, honour related crimes, acid attacks or witch-hunting who have reached out or been referred to the OSC will be provided with specialized services.", 
    "eligibility" : ["A woman affected by violence can access OSC in the following manner:", "By herself", "Through any person including any public spirited citizen, public servant (as defin ed under section 21 of Indian Penal Code, 1860), relative, friend, NGO, volunteer etc.", "Through Women Helpline integrated with police, ambulance and other emergency response helplines."], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "22",
    "name": "Samartha Karnataka",
    "category" :["Students", "Skill Development"],
    "gender":["All"],
    "disability":["No"],
    "age":[13],
    "ageLowerLimit": 13, 
    "ageHigherLimit" : 130,
    "shortDescription" : "This Scheme is lauched by Govt. of Karnataka to provide both skill and job for youths.", 
    "longDescription" : "", 
    "eligibility" : ["One should turn 13 year "], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "23",
    "name": "PM Kaushal Viakas Yojana",
    "category" :["Students", "Skill Development"],
    "gender":["All"],
    "disability":["No"],
    "age":[18],
    "ageLowerLimit": 18, 
    "ageHigherLimit" : 130,
    "shortDescription" : "This is the flagship scheme of the Ministry of Skill Development & Entrepreneurship (MSDE) implemented by National Skill Development Corporation.", 
    "longDescription" : "The objective of this Skill Certification Scheme is to enable a large number of Indian youth to take up industry-relevant skill training that will help them in securing a better livelihood. Individuals with prior learning experience or skills will also be assessed and certified under Recognition of Prior Learning.", 
    "eligibility" : ["An Indian youth, college/school dropout.", "Be at least 18 years of age.", "Have a valid identity proof such as a Voter’s ID, Aadhaar Card, or a Bank account.", "Have an auto-debit Bank of India account", "vails the monetary award for once during the function of PMKVY.", "Sector Skill Councils (SSC) may also define any other criteria for the respective job roles."], 
    "implementedBy" : "", 
    "link" : "http://www.pmkvyofficial.org/"
    },
    {
    "id": "24",
    "name": "SANKALP (Skills Acquisition and Knowledge Awareness for Livelihood Promotion)",
    "category" :["Students", "Skill Development"],
    "gender":["All"],
    "disability":["No"],
    "age":[18],
    "ageLowerLimit": 18, 
    "ageHigherLimit" : 130,
    "shortDescription" : "This project is to bolster the vocational training given by the institutions at both state and national level.", 
    "longDescription" : "The objective of the scheme is to form a team consisted of efficient trainers and assessors. The aim is to establish a robust system. A system both at state and national level will be efficient enough so that it can monitor the activities like, skill training, evaluation of the candidates, and the training program.", 
    "eligibility" : ["The scheme is only applicable for the people of India, and in order to start a vocational training the candidate needs to be 18 years old."], 
    "implementedBy" : "", 
    "link" : "https://sankalp.msde.gov.in/#/web/web-home "
    },
    {
    "id": "25",
    "name": "STAR ( Standard Training Assessment and Reward Scheme )",
    "category" :["Students", "Skill Development"],
    "gender":["All"],
    "disability":["No"],
    "age":[18],
    "ageLowerLimit": 18, 
    "ageHigherLimit" : 130,
    "shortDescription" : "The Ministry of Skill Development and Entrepreneurship initiated the National Skill Certification and Monetary Reward through Standard Training Assessment and Reward Scheme (STAR).", 
    "longDescription" : "The scheme encourages the youth by providing a training program to incorporate market-driven skills and increase problem-solving methods to meet the demand of highly competitive markets. Upon successful completion of the training, the members are provided with monetary rewards and certificates.", 
    "eligibility" : ["The applicant should be an Indian citizen", "The applicant should have completed 10th grade", "The applicant registering for the course must be 18 years or above"], 
    "implementedBy" : "", 
    "link" : ""
    },
    {
    "id": "26",
    "name": "E Shram portal",
    "category" :["Unorganised Labour"],
    "gender":["All"],
    "disability":["No"],
    "age":[16],
    "ageLowerLimit": 16, 
    "ageHigherLimit" : 59,
    "shortDescription" : "The Ministry of Labour & Employment which is one of the oldest and important Ministries of the Government of India, is continuously working on improving life and dignity of Labour force of country ", 
    "longDescription" : "By protecting & safeguarding the interest of workers, promotion of welfare and providing social security to the Labour force both in Organized and Unorganized Sectors by enactment and implementation of various Labour Laws, which regulate the terms and conditions of service and employment of workers.", 
    "eligibility" : ["Any worker who is unorganized and aged between 16-59, is eligible to register on the eSHRAM portal."], 
    "implementedBy" : "", 
    "link" : "https://eshram.gov.in/e-shram-portal"
    },
    {
    "id": "27",
    "name": "Shramika Karnataka",
    "category" :["Unorganised Labour", "Pension"],
    "gender":["All"],
    "disability":["No"],
    "age":[18],
    "ageLowerLimit": 18, 
    "ageHigherLimit" : 130,
    "shortDescription" : "Nearly 2.4 cr un organized workers are there in Karnataka. There are more than 23 types of unorganized workers in our state, To bring them under one umbrella is the main aim of the scheme. ", 
    "longDescription" : "Objective of the scheme. • Pension and  Providing ESI facility  • Responsible for the education of their children  • Providing skills to unorganized workers", 
    "eligibility" : ["All un organized workers aged 18 year old. "], 
    "implementedBy" : "", 
    "link" : ""
    }
    
  ]
  

module.exports =  data;